services:
  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./app:/app
    develop:
      watch:
        - action: rebuild
          path: Pipfile
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: docker-compose.yaml
  postgres:
    image: postgres:13.3
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pantera!!!
      POSTGRES_DB: hello
    ports:
      - "5432:5432"
    volumes:
      - ./database/mock.sql:/docker-entrypoint-initdb.d/init.sql
