name: "Linter: Terraform fmt"

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Check if Terraform is formated correctly
        run: |
          tffmt=$(terraform fmt --recursive --check .)
          if [[ ! -z "$tffmt" ]]; then echo "Missing formating on code, run terraform fmt --recursive . on files:\n\n$tffmt"; fi
